### ISSUE TITLE
atendimento ao protocolo de segurança TLS 1.2

### ISSUE THREAD

**Issue by deyvsonaguiar** [zabaala/moip#2]
Recentemente peguei um job que preciso implementar esse sistema de pagamentos num Rest Laravel, de acordo com a sandbox.moip descreve essa mensagem sobre o protocolo de segunça TLS 1.2, essa biblioteca já está atualizada para utilizar esse padrão de segurança apartir da versão 1.2?

Atenção, fique ligado na atualização do protocolo de segurança TLS 1.2

Temos um protocolo que é responsável pela transmissão de informações do seu site para o Moip com segurança. Esse protocolo é chamado TLS e a partir do dia 30/06/2018 ele será atualizado para a versão 1.2 e todas as versões anteriores (1.0 e 1.1) serão desativadas.

Não esqueça de verificar o seu sistema e garantir que ele está pronto para o TLS 1.2, caso contrário o Moip poderá parar de funcionar no seu site.

Consulta feita em 22/06/2018: https://dev.moip.com.br/

**Comment by joelsantosbr** [comment]
@deyvsonaguiar Eu utilizo esse pacote também e na verdade esse TLS 1.2 é uma tecnologia que seu servidor tem que ter e não o pacote. Confirme com o suporte da sua hospedagem. [Clique aqui e utilize essa ferramenta de análise para verificar as configurações do seu servidor.](https://www.ssllabs.com/ssltest/)
