### ISSUE TITLE
Erro de Unauthorized

### ISSUE THREAD

**Issue by fernandomacoli** [zabaala/moip#3]
Criado um projeto laravel 5.8.* e feito a instalação do pacote.
Projeto será somente api.
Configurado o token e key no .env e ao fazer a chamada da listagem de planos me retorna o erro Unauthorized.
Falta algo a se configurar?

Código do controller abaixo, bem simples.
 
![image](https://user-images.githubusercontent.com/1572651/74462198-97e5a480-4e6e-11ea-918f-59792bfc10b9.png)

**Comment by zabaala** [comment]
A conta que você está utilizando é uma conta sandbox ou uma conta production?

**Comment by fernandomacoli** [comment]
sandbox

![image](https://user-images.githubusercontent.com/1572651/74463315-6ec61380-4e70-11ea-8ebb-73656e8ac506.png)

**Comment by zabaala** [comment]
Eu me refiro à conta no Moip. Na Wirecard, no caso. Você criou uma conta lá no ambiente de sandbox ou no ambiente de produção?

**Comment by fernandomacoli** [comment]
Sandbox

**Comment by zabaala** [comment]
Acabei de fazer um teste num novo projeto Laravel, com a versão 5.8, e o pacote funcionou corretamente.

Muito provavelmente, você esteja informando as credenciais erradas.

Recomendo que as verifique novamente e se certifique, também, que o ambiente que você está utilizando as credenciais, correspondem ao ambiente configurado no ambiente.

Por fim, recomendo forçar a leitura das configurações com ```php artisan config:clear```. Não acho que seja isso, mas não custa nada tentar.
